### ISSUE TITLE
wikiの編集について

### ISSUE THREAD

**Issue by RuskEocssar** [MCJE-Tech-Shares/Datapack-WIki#5]
wikiの記事を書くとき
- Pageを追加して好きなように記事を書き、そのリンクを_sidebar.mdの対応ジャンルのところに追加する
- 対応するジャンルが無さそうだったら適度に追加や変更をしてもらっていいです
- Pageが順番通りに並ぶようにしておきたいので先頭に記事番号を付ける方針
- 記事番号は <ジャンルNo.何番目> 例)→ 01.001, 05.003　（いまのところ）
- wiki右下のurlからローカルにクローンしてVSCodeで書くのが楽

ファイル類をアップするなら
- wikiの記事分類に合わせてフォルダを分ける
- 名前空間、ストレージ、スコアボード/ホルダー、UUID等が他のデータパックと競合しない作りになってさえいればヨシ

**Comment by intsuc** [comment]
Home.mdと_sidebar.mdについての提案なのですが、コマンドメモのセクションは_sidebar.mdのみでHome.mdの方には無くても良いのではないかと思います。

**Comment by RuskEocssar** [comment]
確かによくよく思い出せばwikiってそういう作りが多いですね... homeを画像とか説明とかでにぎやかにしてリンクは消しておきましょうか
