### ISSUE TITLE
実行functionの記載漏れ

### ISSUE THREAD

**Issue by Suyarumi** [MCJE-Tech-Shares/Datapack-WIki#6]
[mchを使ったベンチマーク#タグ,スコア,チームの付け消し](https://github.com/MCJE-Tech-Shares/Technical-Note/wiki/11.001.Benchmark#%E3%82%BF%E3%82%B0%E3%82%B9%E3%82%B3%E3%82%A2%E3%83%81%E3%83%BC%E3%83%A0%E3%81%AE%E4%BB%98%E3%81%91%E6%B6%88%E3%81%97)
非常に細かい指摘ですがmchを使ったベンチマークのタグ,スコア,チームの付け消しのところの実行ファンクションCが記載されていません。

**Comment by RuskEocssar** [comment]
ありがとうございます！修正しました！
