### ISSUE TITLE
FandomのMinecraft Wikiは非公式になっている

### ISSUE THREAD

**Issue by intsuc** [MCJE-Tech-Shares/Datapack-WIki#9]
[Minecraft 公式wiki](https://github.com/MCJE-Tech-Shares/Datapack-WIki/wiki#minecraft-%E5%85%AC%E5%BC%8Fwiki)という記述について、[Minecraft Wiki:Community portal/Microsoft status update](https://minecraft.fandom.com/wiki/Minecraft_Wiki:Community_portal/Microsoft_status_update)に書かれているようにFandomのMinecraft Wikiはもう公式のWikiではなくなっていると思います。

以下上記ページの一部の引用です。
> According to that position, all fan websites they do not host are unofficial (which includes, among many others, the wiki), and therefore subject to their branding and community guidelines.
> 
> Being officially declared unofficial does not mean the wiki is no longer in good standing with Mojang or Microsoft.
> 
> Microsoft requires the following to be done:
> - Remove any reference to the wiki being official in every version of the wiki (which includes the international wikis).

**Comment by RuskEocssar** [comment]
しらんかったー！！変更しておきます！
